### PR TITLE
Pass string rather than exception object to log_error()

### PR DESCRIPTION
**Pull request by nobuf**
Fixes https://github.com/mozilla/DeepSpeech/issues/1016

Steps to reproduce the bug:
```shell
mkdir models
./bin/run-ldc93s1.sh --decoder_library_path decode/libctc_decoder_with_kenlm.so --export_dir models
# Second time
./bin/run-ldc93s1.sh --decoder_library_path decode/libctc_decoder_with_kenlm.so --export_dir models
...skip...
Traceback (most recent call last):
  File "DeepSpeech.py", line 1830, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1821, in main
    export()
  File "DeepSpeech.py", line 1747, in export
    log_error(sys.exc_info()[1])
  File "DeepSpeech.py", line 349, in log_error
    prefix_print('E ', message)
  File "DeepSpeech.py", line 329, in prefix_print
    print(prefix + ('\n' + prefix).join(message.split('\n')))
AttributeError: 'exceptions.RuntimeError' object has no attribute 'split'
```

I wasn't sure if using `sys.exc_info()` was intentional, thought `RuntimeError as e` would be a bit more readable.

UPDATE: I found a misspelled variable which kind of related to this issue. Since it's a tiny pull request, I've included it as well.

### CODE REVIEW

File: DeepSpeech.py [hunk 1]
```diff
@@ -1717,7 +1717,7 @@ def export():
             actual_export_dir = os.path.join(FLAGS.export_dir, '%08d' % FLAGS.export_version)
             if os.path.isdir(actual_export_dir):
                 log_info('Removing old export')
-                shutil.rmtree(actual_FLAGS.export_dir)
+                shutil.rmtree(actual_export_dir)
```
Comment (lissyx) [inline DeepSpeech.py]: This should actully be filed as a legit issue and have its own PR, IMHO

**Comment by nobuf** [comment]
I've made a separated issue and PR. Thanks!

File: DeepSpeech.py [hunk 2]
```diff
@@ -1741,8 +1741,8 @@ def export():
                                       output_graph_path, clear_devices, '')
 
             log_info('Models exported at %s' % (FLAGS.export_dir))
-        except RuntimeError:
-            log_error(sys.exc_info()[1])
+        except RuntimeError as e:
+            log_error(e.message)
```
Comment (lissyx) [inline DeepSpeech.py]: This was introduced by 32637c2191692c820f9a79bd185a31877e5539d4

Comment (lissyx) [reply DeepSpeech.py]: At other places, we do `log_error(str(e))`, I guess it would be better to be consistent ?

Comment (nobuf) [reply DeepSpeech.py]: Got it.

**Comment by nobuf** [comment]
Replaced it with casting to string. Thanks!

**Comment by nobuf** [comment]
Squashed :)

**Comment by lissyx** [comment]
Sorry for the delay, and thanks for your patch !
