### PR TITLE
Support for Windows

### LINKED ISSUE #1123: clients for Microsoft Windows
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

is there any plan to have clients for windows ?

### PR DESCRIPTION
**Pull request by carlfm01**
I'm still editing the docs, preparing for CUDA, and finishing the C# examples.

IMPORTANT NOTE: Did not try to train on Windows yet, my initial goal is to enable inference with the clients on Windows.  
Thanks to @reuben and @lissyx, they helped me a lot.

Fixes #1123

### CODE REVIEW

**Comment by carlfm01** [comment]
CUDA ready, I compiled for CUDA 10 with the current PR without extra changes.
With a K80 (Azure Instance) it is 3 times faster than real time :)

**Comment by lissyx** [comment]
@carlfm01 Nice, but I think upstream is still supporting only CUDA 9.0, so we should stick to that :)

**Comment by carlfm01** [comment]
I spent an entire day trying compile with 9.0 and 9.1, I tried with different version of Bazel and VS Build tools but the compilation failed every time, at the moment just works with Bazel 0.17, CUDA 10 with cuDNN 7.3. I also tried with mkl support but seems there is an issue with MS Build Tools.

**Comment by lissyx** [comment]
> I spent an entire day trying compile with 9.0 and 9.1, I tried with different version of Bazel and VS Build tools but the compilation failed every time, at the moment just works with Bazel 0.17, CUDA 10 with cuDNN 7.3. I also tried with mkl support but seems there is an issue with MS Build Tools.

MKL is mostly useful for other usecases than ours, so it's not a big deal. I have not checked the requirements of TensorFlow on Windows wrt CUDA, but it's really important we stick to what upstream supports, otherwise we risk weird bugs and being unable to address them :/

**Comment by carlfm01** [comment]
I tried to stick to CUDA 9.0 but I think is just broken, the nvidia forums is full of issues related to vs build tools and CUDA 9.0. 
Sorry for the delay, well csharp client and examples ready, still on the docs and then I'll get into the builds stuff.

**Comment by carlfm01** [comment]
Should be easier now. I don't know which can be the best aproach to handle BUILDS in the docs since we don't have automated BUILDS for Windows yet, should I upload somewhere and point to them temporally till we got the automated releases ready?

**Comment by lissyx** [comment]
@carlfm01 Yeah, I guess that would be the best way. Adding TaskCluster for Windows is going to be some non-trivial work, but we will definitively do that after we land your PR.

File: native_client/BUILD [hunk 1]
```diff
@@ -18,6 +18,19 @@ KENLM_INCLUDES = [
     "kenlm",
 ]
 
+DECODER_SOURCESWIN = glob([
```
Comment (lissyx) [inline native_client/BUILD]: I guess we should avoid that, and factorize between windows / unix sources, the only difference is OpenFST in fact.

File: native_client/ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/.editorconfig [hunk 2]
```diff
@@ -0,0 +1,11 @@
+; EditorConfig to support per-solution formatting.
```
Comment (lissyx) [inline native_client/ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/.editorconfig]: Is this editor config file really needed ?

Comment (lissyx) [reply native_client/ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/.editorconfig]: And generally speaking, we need a `README.mozilla` that documents how to import / update this.

File: native_client/ctcdecode/mman.h [hunk 3]
```diff
@@ -0,0 +1,55 @@
+/*
+ * sys/mman.h
+ * mman-win32
```
Comment (lissyx) [inline native_client/ctcdecode/mman.h]: Is this written by you or coming from some third-party ?
It's to handle `mmap()` ?

File: native_client/BUILD [hunk 4]
```diff
@@ -1,5 +1,7 @@
 # Description: Deepspeech native client library.
 
+
+
```
Comment (lissyx) [inline native_client/BUILD]: nit: remove empty lines

File: native_client/BUILD [hunk 5]
```diff
@@ -21,12 +23,12 @@ KENLM_INCLUDES = [
 DECODER_SOURCESWIN = glob([
     "ctcdecode/*.h",
     "ctcdecode/*.cpp",
-    "ctcdecode/third_party/openfst-1.6.7-win/src/lib/*.cc"
+    "ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/src/lib/*.cc"
```
Comment (lissyx) [inline native_client/BUILD]: Likely this change should not be in this patch

File: native_client/BUILD [hunk 6]
```diff
@@ -65,10 +67,16 @@ tf_cc_shared_object(
...
-           DECODER_SOURCES,
+            select({
+                "//tensorflow:windows": DECODER_SOURCESWIN,
+                "//conditions:default": DECODER_SOURCES,
+            }),
     # -Wno-sign-compare to silent a lot of warnings from tensorflow itself,
     # which makes it harder to see our own warnings
-    copts = ["-Wno-sign-compare", "-fvisibility=hidden"],
+    copts = select({ 
+        "//tensorflow:windows": [],
```
Comment (lissyx) [inline native_client/BUILD]: Are we sure we don't need any flag? At least for parity with `-fvisibility=hidden` (but I don't know the flag on windows)

File: native_client/BUILD [hunk 7]
```diff
@@ -111,7 +119,10 @@ tf_cc_shared_object(
     ] + if_cuda([
         "//tensorflow/core:core",
     ]),
-    includes = ["c_speech_features", "kiss_fft130"] + DECODER_INCLUDES,
+    includes = ["c_speech_features", "kiss_fft130"] + select({
```
Comment (lissyx) [inline native_client/BUILD]: Maybe it'd be easier to read if we keep `DECODER_INCLUDES` and we move the select when creating the variable ?

File: native_client/BUILD [hunk 8]
```diff
@@ -120,8 +131,14 @@ cc_binary(
     srcs = [
             "generate_trie.cpp",
             "alphabet.h",
-           ] + DECODER_SOURCES,
-    includes = DECODER_INCLUDES,
+           ] + select({
```
Comment (lissyx) [inline native_client/BUILD]: Same here, for readability

File: native_client/deepspeech.h [hunk 9]
```diff
@@ -1,11 +1,15 @@
 #ifndef DEEPSPEECH_H
 #define DEEPSPEECH_H
 
+#if defined _MSC_VER
```
Comment (lissyx) [inline native_client/deepspeech.h]: Isn't this going to be a problem when using `SWIG` on Windows platform ? Shouldn't we move that inside the `ifndef SWIG` branch, instead ?

And maybe add comments on the `endif` lines, now that we have more complexity, to make it easier to follow the code flow

File: native_client/ctcdecode/scorer.cpp [hunk 10]
```diff
@@ -1,6 +1,35 @@
...
+#define R_OK    4       /* Read permission.  */
+#define W_OK    2       /* Write permission.  */ 
+#define F_OK    0       /* Existence.  */
+
+#define access _access    
+#define ssize_t __int64
+#define STDIN_FILENO 0
+#define STDOUT_FILENO 1
+#define STDERR_FILENO 2 
+#endif
```
Comment (lissyx) [inline native_client/ctcdecode/scorer.cpp]: Can you explain a bit those?

File: examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs [hunk 11]
```diff
@@ -0,0 +1,259 @@
+﻿using DeepSpeechClient.Interfaces;
```
Comment (lissyx) [inline examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs]: I'm completely new to C#, so hard to get a good feedback on those. Can you explain why the `Async`-ness ? Is this a requirement from C# or a choice ?

In all bindings we kept that very simple and upto the caller to take care of threading, to make it easier ; in the end, the caller ends up making a new thread for deepspeech for example (that's how I dealt with in Java for example)

File: native_client/BUILD [hunk 12]
```diff
@@ -52,15 +67,22 @@ tf_cc_shared_object(
             "kiss_fft130/_kiss_fft_guts.h",
             "kiss_fft130/tools/kiss_fftr.h",
             "ds_version.h"] +
-           DECODER_SOURCES,
+            select({
```
Comment (reuben) [inline native_client/BUILD]: nit: Instead of doing this select here, you can do it at the definition of `DECODER_SOURCES` and then use a single variable in the rest of the file.

**Comment by reuben** [comment]
Although I now see that TensorFlow has `TensorFlow::WindowsFileSystem` already, so I'm not sure why we need our own mmap API implementation here.

File: native_client/BUILD (hunk 6 above)
Comment (carlfm01) [reply native_client/BUILD]: We dont need these flags, -wno-sign-compare is the equivalent of /w for windows build tools, I will add it, but it still show warnings. 
And for -fvisibility it is related to the exports in [here](https://github.com/carlfm01/DeepSpeech/blob/934b965016f206518840206cff3a7308e016ad06/native_client/deepspeech.h#L8)
we use extern "C" for Windows, so we don't need -fvisibility flag

Comment (lissyx) [reply native_client/BUILD]: Are you 100% sure? We had to do that to make sure embedding code would not end up weird calling wrong symbols. It's an edge case I had experimenting OpenCL on Linux, some protobuf symbols from our code would get picked up by some  xorg / Mesa / OpenCL lib that also used protobuf but with a different version.

Comment (carlfm01) [reply native_client/BUILD]: Yes, MSVC does not export any declaration unless you explicitly tell like [here](https://github.com/carlfm01/DeepSpeech/blob/934b965016f206518840206cff3a7308e016ad06/native_client/deepspeech.h#L5)
For GCC is the opposite, you have to explicitly hidde members.

https://stackoverflow.com/questions/12717991/symbol-visibility-in-windows

**Comment by carlfm01** [comment]
Thanks @reuben , I did few test and yes, we can remove our `mman`.

File: native_client/ctcdecode/scorer.cpp (hunk 10 above)
Comment (carlfm01) [reply native_client/ctcdecode/scorer.cpp]: We don't need this and two more includes, I'll remove them.

File: native_client/BUILD (hunk 7 above)
Comment (carlfm01) [reply native_client/BUILD]: I tried to do it in the same declaration but I missed a  `}` so I decided to move them into two declarations then concatenate to `DECODER_INCLUDES` and DECODER_SOURCES. What do you guys think @reuben

File: native_client/deepspeech.h (hunk 9 above)
Comment (carlfm01) [reply native_client/deepspeech.h]: @lissyx  Yes this is a possible issue, I don't know that much on how SWIG creates its glue code for other langs, I tried to get the build command and test from the taskcluster but is hard to read. If you can share the command that the taskcluster uses I'll test it.

File: examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs (hunk 11 above)
Comment (carlfm01) [reply examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs]: Initially it was synchronous but I started to noticed that if the `feedContent` is called from async context (most of the libs records in async context) and if we call `FinishStream` on an ongoing inference throws an error related to protected memory error,  If we stop the recording and wait for `feedContent` to finish we got weird output.
I decided to create a concurrent queue which is thread safe to handle buffers and prevent to loss the order of the call stack, with the buffer we can call `FinishStream` with unprocessed buffers and wait for them.

I also decided to use async because I want to create the NuGet package from it, and I think it should be ready for use in synchronous and asynchronous scenarios. 
I can add the synchronous equivalent of the methods that don't take care of threading, and then warn about it in the docs. What you think?

File: native_client/deepspeech.h (hunk 9 above)
Comment (carlfm01) [reply native_client/deepspeech.h]: The `makefile ` for the python bindings is not compatible with `mingw64`, we need changes there. I tried with the `makefile ` for python binding but did not work, as long I understand we link to the built .so, so I should work with the current `_MSC_VER`

File: examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs (hunk 11 above)
Comment (lissyx) [reply examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs]: @carlfm01 There are multiple items in your reply, but from my understanding of the first part, it's just that you describe bogus threading use, and it's unrelated to the bindings themselves, but just bad way of using them: the whole lib should run in its own thread.

No idea what's a `NuGet` package. I'm not against async per se, it's just that I would like we keep the bindings as small and as minimal as possible ; in all other languages, the threading "complexity" is left to the user to avoid forcing anything

File: native_client/BUILD [hunk 13]
```diff
@@ -20,30 +18,25 @@ KENLM_INCLUDES = [
...
-    "ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/src/lib/*.cc"
-]) + KENLM_SOURCES
-
-DECODER_INCLUDESWIN = [
-    ".",
-    "ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/src/include",
-    "ctcdecode/third_party/ThreadPool"
-] + KENLM_INCLUDES
-
+OPENFST_SOURCES_PLATFORM = select({
```
Comment (lissyx) [inline native_client/BUILD]: That looks much better :)

File: native_client/BUILD [hunk 14]
```diff
@@ -67,14 +60,11 @@ tf_cc_shared_object(
...
-            select({
-                "//tensorflow:windows": DECODER_SOURCESWIN,
-                "//conditions:default": DECODER_SOURCES,
-            }),
+            DECODER_SOURCES,
     # -Wno-sign-compare to silent a lot of warnings from tensorflow itself,
     # which makes it harder to see our own warnings
     copts = select({ 
-        "//tensorflow:windows": [],
+        "//tensorflow:windows": ["/w"],
```
Comment (lissyx) [inline native_client/BUILD]: Maybe worth moving the `-Wno-sign-compare` comment next to the use, and also commenting that `-fvisibility=hidden` is default on this platform, to make it easier in the future

File: native_client/BUILD [hunk 15]
```diff
@@ -149,15 +130,9 @@ cc_binary(
...
-                "//tensorflow:windows": DECODER_INCLUDESWIN,
-                "//conditions:default": DECODER_INCLUDES,
-            }),
+           ] + DECODER_SOURCES,
+    includes = DECODER_INCLUDES,
     copts = ["-std=c++11"],
     linkopts = ["-lm", "-ldl", "-pthread"],
     defines = ["KENLM_MAX_ORDER=6"],
-)
+)
```
Comment (lissyx) [inline native_client/BUILD]: Useless change of return line

File: native_client/ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/.editorconfig (hunk 2 above)
Comment (lissyx) [reply native_client/ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/.editorconfig]: Even if there's not change ; it's important we know how / where you did pick up things

Comment (reuben) [reply native_client/ctcdecode/third_party/openfst-1.6.7-win/openfst-1.6.7/.editorconfig]: See for example [native_client/kenlm/README.mozilla](https://github.com/mozilla/DeepSpeech/blob/master/native_client/kenlm/README.mozilla)

File: examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs (hunk 11 above)
Comment (carlfm01) [reply examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs]: @lissyx  Ok, I'll move threading stuff to the example

File: native_client/deepspeech.h (hunk 9 above)
Comment (reuben) [reply native_client/deepspeech.h]: I think what @lissyx wants here, and I agree, is to move the `#ifdef _MSC_VER` inside the `#ifndef SWIG`.

**Comment by reuben** [comment]
And thank you for the PR, this is a much requested feature for DeepSpeech so I'm sure a lot of people will make use of it!

File: native_client/deepspeech.h (hunk 9 above)
Comment (carlfm01) [reply native_client/deepspeech.h]: Compiled :)

**Comment by carlfm01** [comment]
Editing the .mozilla for this win port I noticed that I did a mistake in the versions of OpenFST, I think I tried many ports that I totally forget that I'm not using 1.6.7, it is actually 1.6.9 r1.

It contains the license file, I have to check which git file is excluding it. Please allow me some time.

This is the license file.
https://github.com/kkm000/openfst/blob/winport/COPYING

**Comment by carlfm01** [comment]
@reuben Added the license and other related doc files, all should be ready to continue with the doc on how to compile from source.
I'll put it on `NuGet` and hopefully that will bring the attention of a lot potential contributors for Common voice :), it will be interesting since right now all the available NuGet packages are the online speech recognition from big companies

File: native_client/deepspeech.h [hunk 16]
```diff
@@ -1,14 +1,14 @@
 #ifndef DEEPSPEECH_H
 #define DEEPSPEECH_H
 
-#if defined _MSC_VER
-#define DEEPSPEECH_EXPORT extern "C" __declspec(dllexport) 
-#else
 #ifndef SWIG
-#define DEEPSPEECH_EXPORT __attribute__ ((visibility("default")))
+    #if defined _MSC_VER
+        #define DEEPSPEECH_EXPORT extern "C" __declspec(dllexport)
```
Comment (lissyx) [inline native_client/deepspeech.h]: :+1:

File: examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs [hunk 17]
```diff
@@ -25,7 +25,7 @@ static void Main(string[] args)
                 stopwatch.Start();
                 try
                 { 
-                    result = sttClient.CreateModelAsync("output_graph.pbmm", N_CEP, N_CONTEXT, "alphabet.txt", BEAM_WIDTH).GetAwaiter().GetResult();
+                    result = sttClient.CreateModel("output_graph.pbmm", N_CEP, N_CONTEXT, "alphabet.txt", BEAM_WIDTH);
```
Comment (lissyx) [inline examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs]: nit: shouldn't we use CLI args somehow ? otherwise people get forced into naming files

Comment (carlfm01) [reply examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs]: Ok, I'll add args and keep static names for VS Studio runs

File: examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs [hunk 18]
```diff
@@ -38,13 +67,18 @@ static void Main(string[] args)
                 {
                     Console.WriteLine($"Model loaded - {stopwatch.Elapsed.Milliseconds} ms");
                     stopwatch.Reset();
-                    Console.Write("Enable LM [y/n]:");
-                    if (Console.ReadLine().ToLower() == "y")
+                    if (lm == null)
+                        Console.Write("Enable LM [y/n]:");
```
Comment (lissyx) [inline examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs]: That feels weird, but it's your call ; though it'd be better we get consistency with all other CLI tools, so no interactive behavior if possible :)

**Comment by lissyx** [comment]
@carlfm01 that's really getting somewhere ; if @reuben agrees, it'd be great you rebase and squash commits again to get some more readable git history now that most issues have been sorted out :). Could you share some binaries so we can test ?

**Comment by lissyx** [comment]
@carlfm01 Also, I'm not sure it's yet a good idea to publish packages "officially" ; I think it would be better to wait (sorry ...) for automation on TaskCluster to take care of that.

**Comment by lissyx** [comment]
@carlfm01 Can you produce `deepspeech` (CPU only) and `deepspeech-gpu` `NuGet` packages, so I can upload them ?

**Comment by carlfm01** [comment]
Here's https://github.com/carlfm01/deepspeech-tempwinbuilds/releases 

> DeepSpeechConsole.exe --model output_graph.pbmm --alphabet alphabet.txt --lm lm.binary --trie trie --audio arctic_a0024.wav



GPU builds on the way.

**Comment by carlfm01** [comment]
I can compile for compute cap 3.7 using CUDA 9.0 and cuDNN 7, but if add 6.1 or 7.0 it fails.
This is the actual error https://github.com/tensorflow/tensorflow/issues/19198

**Comment by reuben** [comment]
Hm, so it looks like higher compute capability GPU builds will only be possible when we start using the next TensorFlow release. That's unfortunate :/

**Comment by carlfm01** [comment]
Tried with CUDA 9.3 and CUDA 10 but the same result, can't compile with high compute capability .
I'll try the patch soon.

**Comment by carlfm01** [comment]
The patch that is suggested in the issue did not work, I couldn't find which commit upstream fix this issue :/

**Comment by carlfm01** [comment]
Finally, compiled with CUDA 9.0 and cuDNN 7.3.1, I enabled compute capabilities 7.0,6.1,5.2,3.7,6.0 for testing. 
I required to apply the eigen path and add extra environment variable to Windows, I don't know if I should wait for the next upstream release or commit it to the current tf. @lissyx  any suggestion?

The compiled file size is 400MB, I should split it but every compilation takes like 5h, not enough cloud credits to compile all of them :/ 

@lissyx about #1710 no problem, I'll look into that soon.

https://github.com/carlfm01/deepspeech-tempwinbuilds/releases/tag/v1.0

File: examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs (hunk 18 above)
Comment (carlfm01) [reply examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs]: Removed

**Comment by carlfm01** [comment]
Squash for consistent git history, testing the way to include the `tflite_copts()` with the select

File: native_client/BUILD (hunk 6 above)
Comment (carlfm01) [reply native_client/BUILD]: removed the /w, further in the compilation was causing warnings with the /w overridden with W3

File: native_client/BUILD [hunk 19]
```diff
@@ -63,55 +63,60 @@ tf_cc_shared_object(
...
+           DECODER_SOURCES,
+        copts = select({ 
         # -fvisibility=hidden is not required on Windows, MSCV hides all declarations by default
-        "//tensorflow:windows": ["/w"],
+        "//tensorflow:windows": [],
         # -Wno-sign-compare to silent a lot of warnings from tensorflow itself,
         # which makes it harder to see our own warnings
         "//conditions:default": ["-Wno-sign-compare", "-fvisibility=hidden"],
-    }),
+    }) + tflite_copts(),
```
Comment (carlfm01) [inline native_client/BUILD]: @lissyx Is compiling for me, can you take a look?

File: native_client/deepspeech.cc [hunk 20]
```diff
@@ -1,4 +1,7 @@
 #include <algorithm>
+#ifdef _MSC_VER
+  #define _USE_MATH_DEFINES
+#endif
 #include <cmath>
```
Comment (carlfm01) [inline native_client/deepspeech.cc]: Why cmath here and math in the [c_speech_features.cpp](https://github.com/carlfm01/DeepSpeech/blob/68905f72296428e2935f9c3c814bb82a575609e8/native_client/c_speech_features/c_speech_features.cpp#L5) ?

Comment (carlfm01) [inline native_client/deepspeech.cc]: @lissyx Why here `cmath`but in [c_speech_features.cpp](https://github.com/carlfm01/DeepSpeech/blob/d519b7559f526e50f7727d8b55dfa29278fa98ed/native_client/c_speech_features/c_speech_features.cpp#L5) used `math.h`?

Comment (lissyx) [reply native_client/deepspeech.cc]: good question

**Comment by lissyx** [comment]
@carlfm01 I see you did a merge? You should have rebased :'(

File: native_client/deepspeech.cc (hunk 20 above)
Comment (lissyx) [reply native_client/deepspeech.cc]: part of answer: https://github.com/carlfm01/DeepSpeech/commit/5a6afde0e1c1a7458ea89bd991f3875d8f172786

**Comment by lissyx** [comment]
@carlfm01 Next steps for me now would be:
 - try to get rid of the merge in the history,
 - keep the history as clean as possible
 - ensure no regression (I'll have to pick your PR and run it on TaskCluster) on the current codebase.

Then I think we can look at merging that. What's your take @reuben ?

That might feel like a lot of remaining work, but as long as we have proper history, should be quick

**Comment by reuben** [comment]
FWIW I don't care strongly about the merge or the history, we can always squash the PR before merging it. Otherwise, yeah, if this passes tests I think we should merge.

**Comment by carlfm01** [comment]
What about now @lissyx ? Can't get rid of the empty merge that the site creates when resolving the conflict :/

**Comment by lissyx** [comment]
Then I think it's okay. @reuben we merge now?

**Comment by lissyx** [comment]
The test run I did was good

**Comment by reuben** [comment]
:shipit:
